apiVersion: v1
kind: Pod
metadata:
  name: online-inference-resources
  labels:
    app: online-inference-resources
spec:
  containers:
    - image: cherninkiy/made-ml-in-prod-2021-v3:latest
      name: online-inference-resources
      ports:
        - containerPort: 8008
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"