apiVersion: v1
kind: Pod
metadata:
  name: online-inference
  labels:
    app: online-inference
spec:
  containers:
    - image: cherninkiy/made-ml-in-prod-2021-v3:latest
      name: online-inference
      ports:
        - containerPort: 8008