apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
  labels:
    app: online-inference-probes
spec:
  containers:
    - image: cherninkiy/made-ml-in-prod-2021-v4:latest
      name: online-inference-probes
      ports:
        - containerPort: 8008
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      readinessProbe:
        httpGet:
          path: /status
          port: 8008
        initialDelaySeconds: 30
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /status
          port: 8008
        initialDelaySeconds: 120
        periodSeconds: 5